/**
 * =====================================================================
 * FRAUDGUARD — Layer 5: Citizen QR Feedback & Ground-Truth Verification
 * Strict TypeScript Types & Interfaces
 *
 * ⚠️ DEMO & PRIVACY SAFEGUARD NOTICE:
 * 1. Plaintext phone numbers must NEVER be stored, logged, or exposed in UI.
 *    All citizen identifiers must use one-way salted audit tokens (CTZ-TOK-XXXX).
 * 2. Precise GPS coordinates of citizens must NEVER be displayed in the UI.
 *    Only coarse proximity bands (e.g. 'on_site', 'proximate') or rounded
 *    distance estimates are presented.
 * 3. All signals generated by this layer represent advisory discrepancy indicators
 *    for field verification. They do NOT constitute legal proof of fraud.
 * =====================================================================
 */

/**
 * Coarse proximity classification relative to the official project site coordinates.
 * - 'on_site': <= 150 meters (verified physical presence at site)
 * - 'proximate': 151 - 1,000 meters (immediate neighborhood / perimeter)
 * - 'distant': > 1,000 meters (remote submission)
 * - 'unverified': Location permission was not granted or coordinates unavailable
 */
export type ProximityStatus = 'on_site' | 'proximate' | 'distant' | 'unverified';

/**
 * Citizen-observed physical status of the public works project.
 */
export type ObservedProgressStatus =
  | 'not_started'
  | 'in_progress'
  | 'completed'
  | 'abandoned';

/**
 * Specific observation tags or issue categories reported by visiting citizens.
 */
export type CitizenFeedbackIssue =
  | 'no_work_visible'
  | 'substandard_materials'
  | 'delayed_timeline'
  | 'site_abandoned'
  | 'access_blocked'
  | 'signboard_missing';

/**
 * Source of the feedback record.
 */
export type CitizenFeedbackSource =
  | 'synthetic_seed'
  | 'demo_local_storage'
  | 'live_supabase';

/**
 * An individual citizen feedback submission record.
 * PRIVACY: Contains NO raw phone numbers and NO exact citizen coordinates.
 */
export interface CitizenFeedbackRecord {
  /** Unique submission identifier */
  readonly id: string;
  /** Reference to the authentic project ID in PROJECTS (e.g., 'MP-KA-2026-0551') */
  readonly projectId: string;
  /** Privacy-preserving salted token (e.g. 'CTZ-TOK-88A1B2C3'). Derived via one-way hash */
  readonly citizenToken: string;
  /** Submission timestamp in ISO 8601 string format */
  readonly submittedAt: string;
  /** Coarse proximity band relative to project coordinates */
  readonly proximityStatus: ProximityStatus;
  /** Approximate distance in meters rounded to nearest 50m for privacy protection (never exact lat/lon) */
  readonly coarseDistanceMeters?: number;
  /** Observed physical completion state */
  readonly observedStatus: ObservedProgressStatus;
  /** 1-5 star citizen satisfaction / quality rating */
  readonly qualityRating: 1 | 2 | 3 | 4 | 5;
  /** List of observed specific issue tags */
  readonly issuesReported: readonly CitizenFeedbackIssue[];
  /** Optional citizen comment or observation notes */
  readonly comment?: string;
  /** Whether photographic evidence was attached */
  readonly hasPhotoProof?: boolean;
  /** Data origin flag */
  readonly storageSource: CitizenFeedbackSource;
  /** Synthetic demo flag */
  readonly isSynthetic: boolean;
}

/**
 * Severity ranking for discrepancy findings.
 */
export type CitizenDiscrepancySeverity = 'LOW' | 'MEDIUM' | 'HIGH' | 'CRITICAL';

/**
 * Rule-based discrepancy finding comparing citizen ground-truth against official project records.
 * Uses audit-grade, non-accusatory terminology.
 */
export interface CitizenDiscrepancyFinding {
  /** Deterministic rule code (e.g. 'RULE_STATUS_VARIANCE_STALLED') */
  readonly ruleId: string;
  /** Non-accusatory finding label */
  readonly label: string;
  /** Severity classification */
  readonly severity: CitizenDiscrepancySeverity;
  /** Numerical score contribution (0-100 scale impact) */
  readonly scoreImpact: number;
  /** Plain-language factual explanation of the observed variance */
  readonly description: string;
  /** Objective supporting data points (e.g. '3 of 4 on-site citizens report no active works') */
  readonly evidence: readonly string[];
  /** Actionable next step for public works oversight */
  readonly recommendedAction: string;
}

/**
 * Aggregated citizen feedback summary and discrepancy profile for a project.
 */
export interface ProjectCitizenSummary {
  /** Authentic project ID */
  readonly projectId: string;
  /** Total number of citizen submissions */
  readonly totalFeedbackCount: number;
  /** Count of submissions verified on-site (<= 150m) */
  readonly onSiteVerifiedCount: number;
  /** Percentage of submissions verified on-site (0-100) */
  readonly onSiteVerifiedPercent: number;
  /** Average citizen quality rating (1.00 - 5.00) */
  readonly averageRating: number;
  /** Count breakdown across observed progress statuses */
  readonly statusDistribution: Readonly<Record<ObservedProgressStatus, number>>;
  /** Frequency breakdown across reported issues */
  readonly issueFrequency: Readonly<Record<CitizenFeedbackIssue, number>>;
  /** Overall citizen discrepancy index (0 - 100, clamped) */
  readonly discrepancyScore: number;
  /** Overall discrepancy severity tier */
  readonly discrepancyLevel: CitizenDiscrepancySeverity;
  /** List of explainable discrepancy findings triggered for this project */
  readonly findings: readonly CitizenDiscrepancyFinding[];
  /** Whether findings warrant priority on-site verification */
  readonly requiresFieldInspection: boolean;
  /** Timestamp of most recent submission */
  readonly lastSubmittedAt?: string;
  /** List of sanitized submission records */
  readonly records: readonly CitizenFeedbackRecord[];
}

/**
 * In-memory raw submission payload captured at the citizen submission boundary.
 * Phone and coordinates are used strictly in memory to compute the token and coarse distance,
 * and are NEVER persisted or returned.
 */
export interface RawCitizenSubmissionInput {
  readonly projectId: string;
  /** 10-digit mobile number input — used strictly in memory for token derivation then discarded */
  readonly rawPhoneInput: string;
  /** User-provided OTP code — verified in demo or live mode then discarded */
  readonly otpInput: string;
  readonly observedStatus: ObservedProgressStatus;
  readonly qualityRating: 1 | 2 | 3 | 4 | 5;
  readonly issuesReported: readonly CitizenFeedbackIssue[];
  readonly comment?: string;
  readonly hasPhotoProof?: boolean;
  /** In-memory citizen coordinates — evaluated against project coords and never saved */
  readonly citizenCoordinates?: {
    readonly latitude: number;
    readonly longitude: number;
  } | null;
  /** Project site coordinates */
  readonly projectCoordinates?: {
    readonly latitude: number;
    readonly longitude: number;
  } | null;
}
